- Cargo.toml
- src/change_frag.rs
- src/lib.rs
- src/main.rs
- src/pr_title.rs
* fix(change_frag.rs): rename log_update.rs to change_frag.rs and update imports and references accordingly
* feat(pr_title.rs): add PrTitle struct and parse function for parsing PR titles
* feat(main.rs): update imports and references to use pcu_lib instead of log_update
* feat(lib.rs): add module declarations for change_frag and pr_title and re-export them from the library
* test(pr_title.rs): add unit tests for parsing PR titles
> refactor: create lib and seperate modules

- src/main.rs
- src/pr_title.rs
Better reflects the final role of the data generated.
- fix(main.rs): fix typo in println statement, change pr_title.description to pr_title.entry
- refactor(pr_title.rs): rename kind field to section, description field to entry
- refactor(pr_title.rs): update references to kind and description fields to section and entry respectively
> refactor: change kind and description to section and entry

- src/client.rs
- src/main.rs
- feat(client.rs): add support for PCU_BRANCH environment variable and store it in the Client struct
- fix(main.rs): use the branch value from the Client struct instead of directly accessing the environment variable
> chore: move branch identification to client

- src/client.rs
- src/main.rs
- feat(client.rs): add support for PCU_PULL_REQUEST environment variable and extract pull_release, pr_number, owner, and repo information from it
- fix(main.rs): pass client object to changelog_update function and use client methods to retrieve pull_release, pr_number, owner, and repo information
> chore: move pull_request to client

- src/client.rs
- src/main.rs
* fix(client.rs): change return type of `repo_status` method from `Result<(), Error>` to `Result<String, Error>`
* feat(client.rs): add `print_long` function to print out git status in long form and return the output as a string
* feat(main.rs): print repository state after updating changelog
> refactor: string output from repo status

- src/client.rs
* chore(client.rs): refactor print_long function to append file paths to output variable instead of printing directly
> fix: missing untracked file names

- src/client.rs
* fix(client.rs): fix branch_remote variable to include "origin/" prefix before branch name
> fix: prefix branch with origin

- src/client.rs
* fix(client.rs): change return type of commit_changelog method from Result<(), git2::Error> to Result<String, git2::Error>
* feat(client.rs): add printing of branch divergence information in commit_changelog method
> chore: look at differences

- src/client.rs
* fix(client.rs): change return type of commit_changelog and push_changelog methods from Result<String, git2::Error> to Result<String, Error>
* feat(client.rs): add branch_list method to check branch before pushing changes
> chore: check branch list

- src/client.rs
* fix(client.rs): fix credentials callback to use the username from the URL instead of hardcoded value 'git'
* chore(client.rs): update log message to indicate that credentials are set based on the ssh key agent
> chore: use username_from_url

- CHANGELOG.md
- src/client.rs
- src/main.rs
- src/pr_title.rs
* feat(client.rs): update the `update_changelog` function to return an `Option<(ChangeKind, String)>` instead of `Result<(), Error>`
* feat(main.rs): modify `changelog_update` function to handle the updated return type of `update_changelog` function in `Client` struct. Print the proposed addition to the change log if an update is required. Print "No update required" if no update is needed.
* feat(pr_title.rs): modify `update_changelog` function in `PrTitle` struct to return an `Option<(ChangeKind, String)>` instead of `()` to indicate whether an update was made or not. Return `None` if the changelog already contains the entry. Return `Some((section, entry))` if an update was made.
> feat: Return early if the changlog has been updated already

- .circleci/config.yml
- CHANGELOG.md
- src/client.rs
* fix(config.yml): remove exclamation mark from BOT_SIGN_KEY variable in git config command
* chore(client.rs): comment out unused SIGNATURE_KEY constant
* refactor(client.rs): remove unused code and commented out code
* fix(client.rs): fix commit creation by using git_repo.commit instead of git_repo.commit_create_buffer
* refactor(client.rs): remove unused variables and print statements
* refactor(client.rs): remove unused code for setting target commit
> refactor: align var and restore simple commit without signing

- src/client.rs
* chore(client.rs): replace println! statements with log::trace! statements
* refactor(client.rs): format output string in print_long function
> chore: move all but current println to logging

- .circleci/config.yml
- CHANGELOG.md
- src/main.rs
Restrict modules reported when logging to based on command line to those logs generated by this crate. 
* chore(main.rs): refactor logging configuration in get_logging function
* fix(main.rs): fix println statement in get_logging function
* feat(main.rs): add constants for log environment variables
> feat: allow log environment variables to override command line

- CHANGELOG.md
- src/main.rs
Build out the CII to provide a  sign option  to determine how  pcu should sign the commit with the change log update. Create an enum for the signing options including initially `none` (not signed) and `gpg` . Gpg is the default option. 
While it is desibable to have the commits signed to authenticate the changes on the repository this may not be an options that can be configured by every user (or that every user desires) and therefore an unsigned option should be allowed. 
Initial setup
> feat: add Sign enum and sign field to Cli struct

- .circleci/config.yml
- CHANGELOG.md
- src/client.rs
- src/main.rs
Operartionalise the option that was provided earlier by matching the choice made and calling the relevant client method.
* refactor(client.rs): rename commit_changelog_signed to commit_changelog_gpg
* feat(main.rs): add sign parameter to run_update function
* feat(main.rs): add match case for GPG and None sign types in run_update 
* feat(main.rs): make sign argument optional in Cli struct
* fix(main.rs): set default value for sign if not provided
* fix(main.rs): correct the logging level assignment in get_logging function
While it is desibable to have the commits signed to authenticate the changes on the repository this may not be an options that can be configured by every user (or that every user desires) and therefore an unsigned option should be allowed. 
Initial setup
> feat: add match for sign types in run_update function

- src/client.rs
* fix(client.rs): fix type annotation for msg variable to String
* fix(client.rs): pass msg variable as reference in commit and commit_create_buffer methods
* fix(client.rs): pass msg variable as reference in set_target method
> fix: fix type annotation for msg variable to String and pass as ref

- CHANGELOG.md
- src/pr_title.rs
* fix(pr_title.rs): update log messages for existing and non-existing changelog entries
* feat(pr_title.rs): add logic to create a default changelog if it does not exist
> feat: create unreleased section if it does not exist

- .circleci/config.yml
- CHANGELOG.md
* chore(circleci): update changelog command to use absolute path for pcu binary
> chore: user cargo home bin version of pcu

- CHANGELOG.md
- src/main.rs
* fix(main.rs): add return statement when encountering an error while updating the changelog
> fix: ensure that final error state fails pcu application

- CHANGELOG.md
- src/client.rs
- src/error.rs
- src/main.rs
- src/pr_title.rs
* fix(client.rs): handle potential error when parsing PR title in create_entry method
* fix(error.rs): add handling for RegexError in Error enum
* fix(pr_title.rs): change parse method to return Result and handle potential errors in parsing and updating changelog
* test(pr_title.rs): add tests for parsing PR titles with different scopes and types
* test(pr_title.rs): add tests for parsing PR titles with breaking changes and different scopes
* fix(client.rs): add clippy lint to handle unnecessary question mark operator
* fix(error.rs): import OsString from ffi module to handle InvalidPath error
* fix(main.rs): refactor sign variable initialization using unwrap_or_default method
* fix(pr_title.rs): handle Result type for update_changelog method and return error for invalid path
> refactor: remove unwrap from string conversion of OsStr value

- CHANGELOG.md
- src/main.rs
* feat(main.rs): add string constants for update status
* refactor(main.rs): change run_update function to return a string indicating update status
* feat(main.rs): print update status after changelog update
> feat: print message when changelog updated

- .circleci/config.yml
- CHANGELOG.md
- src/client.rs
- src/main.rs
Replaces the previous "updated" and "not updated" messages.
* feat(main.rs): add early_exit flag for signaling an early exit
* refactor(main.rs): replace string constants UPDATED and NOT_UPDATED with ClState enum
* fix(main.rs): update run_update function to return ClState instead of String
* feat(main.rs): add SIGNAL_HALT constant for early exit signal
> feat: add early_exit flag for signaling an early exit

- CHANGELOG.md
- src/client/mod.rs
- src/main.rs
* feat(client/mod.rs): add logging for octocrab creation
* fix(client/mod.rs): improve logging message for updating unreleased section
* fix(main.rs): move update_unreleased method inside update_changelog condition
> chore: add logging for octocrab creation

- .circleci/config.yml
- CHANGELOG.md
- src/client/mod.rs
* feat(.circleci/config.yml): add bot-check context to make_release workflow
* fix(client/mod.rs): use local octocrab instance for generating release notes
> fix: use local octocrab instance add bot-check context to make_release workflow

- CHANGELOG.md
- src/client/mod.rs
> fix: format version string with 'v' prefix in generate_release_notes method

- CHANGELOG.md
- src/client/mod.rs
* fix(client/mod.rs): change commit_changelog_gpg method to mutable
* feat(client/mod.rs): enhance tag reference handling in Client implementation
> fix: change commit_changelog_gpg method to mutable

- CHANGELOG.md
- src/client/mod.rs
> fix: modify version_tag reference format in git_repo.find_reference method

- CHANGELOG.md
- src/client/mod.rs
* feat(client/mod.rs): add list_tags function to list git refs
* refactor(client/mod.rs): replace direct command call with list_tags function call in log trace
> chore: list the tags in the git repo

- CHANGELOG.md
- src/client/mod.rs
> fix: prepend 'v' to version_tag before tagging commit

- .circleci/config.yml
- CHANGELOG.md
- src/client/git_ops.rs
- src/client/mod.rs
- src/lib.rs
- src/main.rs
- src/pr_title.rs
* - Create a new module `git_ops.rs` and move git related operations from `client/mod.rs` to the new module
* - Implement `GitOps` trait for `Client` in `git_ops.rs`
* - Update `client/mod.rs` to import and expose `GitOps`
* - Update `lib.rs` to expose `GitOps`
* - Update `main.rs` to import `GitOps`
> feat(client): extract git operations to a separate module

- CHANGELOG.md
- src/client/git_ops.rs
- src/client/mod.rs
* refactor(git_ops.rs, mod.rs): move get_commitish_for_tag method from mod.rs to git_ops.rs
* fix(git_ops.rs): replace version parameter with tag in get_commitish_for_tag method
* feat(mod.rs): add tag formatting in Client implementation
> fix: replace version parameter with tag in get_commitish_for_tag method

- CHANGELOG.md
- src/client/git_ops.rs
* feat(git_ops.rs): enable version tagging functionality in push_changelog method
* fix(git_ops.rs): improve logging for tag tracing in push_changelog method
> chore: restore tag push

- CHANGELOG.md
- src/client/git_ops.rs
* fix(git_ops.rs): modify default value for file_contents in list_tags function
* refactor(git_ops.rs): change format of output string in list_tags function
> chore: check if file is empty or error in read

- CHANGELOG.md
- src/client/git_ops.rs
* feat(git_ops.rs): add recursive listing of git refs
* fix(git_ops.rs): correct filename logging in list_tags function
> chore: correct filename logging in list_tags function

- CHANGELOG.md
- src/client/mod.rs
- src/main.rs
- src/ops/make_release.rs
- src/ops/update_from_pr.rs
- src/pr_title.rs
* feat(client/mod.rs): add ChangelogParseOptions to Client struct
* feat(main.rs): add default value for version_prefix in settings
* refactor(make_release.rs, update_from_pr.rs, pr_title.rs): use ChangelogParseOptions from Client struct
* test(pr_title.rs): update tests to use ChangelogParseOptions
> feat: add ChangelogParseOptions to Client struct and default value for version_prefix

- CHANGELOG.md
- src/main.rs
* feat(main.rs): add logging for GPG and None signing options
* fix(main.rs): pass version to commit_changelog_gpg and commit_changelog methods
> fix: pass version to commit_changelog_gpg and commit_changelog methods

- CHANGELOG.md
- src/ops/git_ops.rs
- src/ops/make_release.rs
* feat(git_ops.rs): add trace log for owner and repo in get_commitish_for_tag function
* feat(make_release.rs): add debug log for octocrab instance creation in MakeRelease implementation
> chore: track get committish

- .circleci/config.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/client/mod.rs
- src/client/pull_request.rs
* refactor(config.yml): reduce pcu_verbosity level from "-vvvv" to "-vvv"
* refactor(client/mod.rs): move git_api instantiation to top of Client implementation
* feat(client/mod.rs): add debug log when getting GitHub API instance
* refactor(client/mod.rs): change debug log message when using personal access token for authentication
* refactor(client/pull_request.rs): pass GitHubAPI instance to new_pull_request_opt function
* refactor(client/pull_request.rs): remove redundant GitHubAPI instantiation in new_pull_request_opt function
> fix: remove redundant GitHubAPI instantiation in new_pull_request_opt function

- CHANGELOG.md
- Cargo.lock
- src/main.rs
* refactor(main.rs): change print_changelog function to return string instead of printing directly
* refactor(main.rs): use log::trace for changelog output instead of checking log level manually
> refactor: change print_changelog function to return string instead of printing directly

- CHANGELOG.md
- src/cli/main.rs
- src/lib/ops/git_ops.rs
* feat(cli/main.rs, lib/ops/git_ops.rs): add stage_files function to GitOps trait and implement it in Client
* feat(cli/main.rs): stage files in workdir before checking staged files
> feat: add stage_files function to GitOps trait and implement it in Client

- .circleci/config.yml
- CHANGELOG.md
- src/cli/cli.rs
- src/cli/main.rs
- src/lib/lib.rs
- src/lib/ops/git_ops.rs
- src/lib/ops/mod.rs
* refactor(cli.rs, main.rs, lib.rs, git_ops.rs, mod.rs): move Sign enum from cli.rs to git_ops.rs
* feat(git_ops.rs): add commit_staged function to GitOps trait
* refactor(main.rs): replace sign match with commit_staged function call
> feat: add commit_staged function to GitOps trait

- CHANGELOG.md
- src/lib/ops/git_ops.rs
* refactor(git_ops.rs): remove get_authenticated_remote method and integrate its functionality into push_commit method
* style(git_ops.rs): remove unnecessary imports and adjust code formatting
> fix: integrate get_authenticated_remote into push_commit method

- CHANGELOG.md
- src/lib/client/graphql/label.rs
- src/lib/client/graphql/mod.rs
- src/lib/client/graphql/repo.rs
- add `repo.rs` for GraphQL repository ID retrieval
- update `label.rs` to handle missing labels and retrieve repository ID
- include `repo` module in `mod.rs`
> feat: add repository ID retrieval and improve label handling

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/commit.rs
- move run_commit function to a separate module for better organization
- update main.rs to use the new module path for run_commit function
> ♻️ refactor(cli): modularize commit command handling

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/push.rs
- remove inline `run_push` function from main.rs and relocate it to a dedicated push module
- update the cli module to include `run_push` from the new push module for cleaner code organization
- improve code maintainability by separating concerns and enhancing modularity
> ♻️ refactor(cli): modularize push command handling

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/release.rs
- extract release-related functions into a new `release.rs` module for better code organization
- update imports and function calls to reflect the new module structure
🔥 remove(main.rs): delete unused functions for cleanup
- remove unused functions `push_committed`, `commit_changed_files`, `run_release`, `release_semver`, `release_workspace`, `release_package`, and `print_changelog` from `main.rs`
- clean up imports to remove dependencies on deleted functions
> ♻️ refactor(cli): modularize release logic into separate module

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/push.rs
- move Push struct and its methods to cli/push.rs for better organization
- change run_push function to be a method of the Push struct for encapsulation
♻️ refactor(main): update push command execution
- modify main.rs to call the new run_push method on Push struct
> ♻️ refactor(cli): centralize push command implementation

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/commit.rs
- relocate Commit struct and methods to cli/commit.rs for better organization
- update run_commit function to be a method of Commit struct
- adjust main.rs to use the new method approach for commit command
> ♻️ refactor(cli): move commit command logic to cli/commit.rs

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/label.rs
- move Label struct implementation from cli.rs to cli/label.rs
- integrate run_label method within Label struct for better cohesion
✨ feat(cli): improve label command flexibility
- add Parser derive for Label struct to enhance command parsing
- allow optional label customization using author, label, desc, and colour fields
> ♻️ refactor(cli): enhance label command structure

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/release.rs
- move Release struct definition to `cli/release.rs` for modularity
- implement run_release as a method of Release for consistency
- separate workspace and package release logic into distinct methods
- improve code readability and maintainability by refactoring logic
🐛 fix(release): correct release command execution
- modify run_release method call to adhere to new release structure
- ensure proper invocation of release methods within main function
> ♻️ refactor(release): restructure release command handling

- CHANGELOG.md
- src/bin/main.rs
- src/cli.rs
- src/cli/pull_request.rs
- move `Pr` struct definition from `cli.rs` to `pull_request.rs`
- integrate `run_pull_request` method into `Pr` struct for better encapsulation
♻️ refactor(main): update pull request command to use method on `Pr`
- change invocation of pull request command to use the method on the `Pr` struct
> ♻️ refactor(cli): migrate `Pr` struct and method to `pull_request.rs`

- CHANGELOG.md
- src/cli.rs
- src/cli/commit.rs
- src/cli/pull_request.rs
- src/cli/release.rs
- src/ops/git_ops.rs
- remove `commit_changed_files` function from cli module
- utilize GitOps trait for commit operations
🐛 fix(git_ops): add commit function to GitOps trait
- implement `commit_changed_files` function in GitOps trait
- ensure consistent commit handling across modules
🔧 chore(dependencies): adjust import paths for owo_colors
- move owo_colors imports from cli to git_ops module
> ♻️ refactor(cli): remove duplicate commit function

- CHANGELOG.md
- src/cli.rs
- src/cli/bsky.rs
- src/cli/bsky/commands/cmd_draft.rs
- src/cli/bsky/commands/cmd_draft/draft.rs
- src/cli/bsky/commands/cmd_post.rs
- add 'store' argument to specify directory for storing Bluesky posts
- set default storage directory to 'BSKY_POSTS_DIR' for convenience
> ✨ feat(cli): add storage directory option for Bluesky posts

- .circleci/config.yml
- CHANGELOG.md
- eliminate wasmtime and wasmpack version checks to streamline the CI process
> 🔧 chore(ci): remove unused version checks in CircleCI config

- .circleci/config.yml
- CHANGELOG.md
- src/cli/bsky/commands/cmd_post/poster.rs
- change function from checking CI variable to checking TESTING variable
- add debug log to display testing status
👷 ci(circleci): update toolkit orb version and add testing export
- bump toolkit orb version from 2.8.1 to 2.8.3
- export TESTING environment variable in CI jobs for consistent testing
> ♻️ refactor(cli): replace CI check with testing check

- CHANGELOG.md
- src/cli/pull_request.rs
- src/cli/push.rs
- src/cli/release.rs
- src/ops/git_ops.rs
- introduce bot user name environment variable for push_commit
- enhance logging to debug bot user name being used
- modify function signature to accept bot user name parameter across cli modules and git operations
> ✨ feat(cli): add bot user name for push_commit

- CHANGELOG.md
- src/client/graphql/get_tag.rs
- change committed_date type to DateTime<Utc> for timezone support
- update imports to include DateTime and Utc from chrono
✅ test(graphql): add test for GraphQLGetTag
- add test to verify parsing of GraphQL response
- ensure correct parsing of committedDate in test data
> ✨ feat(graphql): update committed_date to DateTime<Utc>

- CHANGELOG.md
- src/cli/release.rs
- src/error.rs
- log an error and return missing semver error if semver is not set
- improve logging for release process steps
✨ feat(error): add missing semver error
- introduce MissingSemver error for release process
- enhance error handling with a clear message
> 🐛 fix(release): add semver requirement check

- CHANGELOG.md
- src/bin/main.rs
- src/cli/pull_request.rs
- introduce hide_no_pull_request flag to suppress pull request failure messages
- improve CI integration by allowing silent failure handling
🐛 fix(main): add error logging on main function failure
- log errors when main function encounters an error to improve debugging
> ✨ feat(cli): add hide_no_pull_request option to Pr

- CHANGELOG.md
- src/cli/pull_request.rs
- change error variant from EnvVarPullRequestNotFound to EnvVarPullRequestNotSet
- improve clarity in error messaging for unset pull request environment variable
> 🐛 fix(cli): correct error handling for pull request

- CHANGELOG.md
- renovate.json
- include host rules with token-only auth type for circleci
- enhance automation configuration to support circleci operations
> 🔧 chore(config): add host rules for circleci in renovate

- CHANGELOG.md
- renovate.json
- change renovate extends path to use colon separator for correct config reference
#583
> 🔧 chore(config): update renovate configuration path

- CHANGELOG.md
- src/cli/bsky/commands/cmd_draft/draft/front_matter.rs
- src/cli/bsky/commands/cmd_draft/draft/front_matter/bluesky.rs
- src/cli/bsky/commands/cmd_draft/draft/front_matter/taxonomies.rs
- remove #[allow(dead_code)] attribute
- use self.tags() method directly in loop for consistency
> 🐛 fix(front_matter): correct method call for tag retrieval

- CHANGELOG.md
- src/cli/bsky/commands/cmd_draft.rs
- change triple dots to double dots in basehead to fix commit comparison
- add trace log for commit comparison details
> 🐛 fix(cli): correct basehead format in draft command

- CHANGELOG.md
- src/cli/push.rs
- src/ops/git_ops.rs
- introduce debug logging for branch status in push command
- facilitate easier debugging and status tracking
> 🐛 fix(git_ops): handle empty file lists during staging and committing

- .circleci/config.yml
- CHANGELOG.md
- Cargo.toml
- crates/gen-bsky/README.md
- crates/gen-bsky/src/draft.rs
- crates/gen-bsky/src/front_matter.rs
- crates/pcu/README.md
- change Rust version badge from 1.81+ to 1.87+ to reflect updated requirements
> ♻️ refactor(front_matter): update path handling and remove basename usage

- CHANGELOG.md
- crates/gen-bsky/src/draft.rs
- crates/pcu/src/cli/bsky/commands/cmd_draft.rs
- rename method from add_blog_posts to add_path_or_file for clarity and flexibility
> ♻️ refactor(draft): improve path handling in DraftBuilder

- CHANGELOG.md
- crates/pcu/src/cli/bsky/commands/cmd_draft.rs
- fix condition to correctly handle empty paths scenario
- ensure default path is added when no paths are provided
> 🐛 fix(cli): correct path handling in cmd_draft

- CHANGELOG.md
- Cargo.toml
- crates/pcu/Cargo.toml
- add version "0.0.1" to gen-bsky in Cargo.toml for better version tracking
- remove version from gen-bsky in crates/pcu/Cargo.toml to use workspace version
> 🔧 chore(dependencies): update gen-bsky version specification

- .vscode/ltex.hiddenFalsePositives.en-GB.txt
- CHANGELOG.md
- crates/gen-bsky/src/draft.rs
- add new rule for EN_COMPOUNDS_POST_PROCESSING to ltex.hiddenFalsePositives.en-GB.txt
> ✅ test(draft): add comprehensive tests for DraftError variants

- CHANGELOG.md
- crates/gen-bsky/src/draft.rs
- crates/gen-bsky/src/draft/draft_builder.rs
- add test-only methods to access base_url and root for DraftBuilder
> ✅ test(draft): add extensive tests for builder() method
