src/main.rs

- feat(main.rs): add support for printing PR number and project owner/repo information
- fix(main.rs): fix printing PR ID instead of PR number in the println statement

feat: finding changelog file name

---

src/main.rs

- fix(main.rs): change environment variable names from CIRCLE_BRANCH to PCU_BRANCH, CIRCLE_PROJECT_USERNAME to PCU_PROJECT_USERNAME, CIRCLE_PROJECT_REPONAME to PCU_PROJECT_REPONAME, CIRCLE_PULL_REQUEST to PCU_PULL_REQUEST
- feat(main.rs): update console log messages in changelog_update function

feat: env variables independent of CI

---

src/main.rs

- chore(main.rs): refactor code to use constant for CHANGELOG_FILENAME
- feat(main.rs): update change log with pull request title

feat: update change log

---

src/pr_title.rs

- fix(pr_title.rs): fix issue with parsing changelog file when it does not exist
- feat(pr_title.rs): add logic to create a new changelog file if it does not exist

feat: create change log if it was not found

---

Cargo.toml
src/main.rs

- chore(Cargo.toml): add git2 crate as a dependency
- feat(main.rs): add commit_changelog function to commit changes to the changelog file
- fix(main.rs): fix import statement for std::env and std::path::Path
- refactor(main.rs): refactor changelog_update function to include commit_changelog function call

feat: commit the updated changelog

---

src/main.rs

- fix(main.rs): change variable name from 'branch' to 'pcu_branch' and update variable name in env::var() call
- feat(main.rs): add support for PCU_REPONAME, PCU_USERNAME, and PCU_PULL_REQUEST environment variables

feat: use app env variables to assure CI independence

---

.circleci/config.yml

- chore(config.yml): add GPG key import step to CircleCI config
- chore(config.yml): add git configuration step to CircleCI config
- chore(config.yml): add optional-builds job to CircleCI config
- chore(config.yml): add pr-changelog-update job to CircleCI config in release workflow

ci: make gpg and git commands and use in changelog update

---

src/main.rs

- fix(main.rs): import PullRequest and PullRequestId from octocrab::models
- feat(main.rs): add pr_id and pr_url to PrTitle struct

feat: set pr id and url to capture in changelog

---

src/main.rs

- chore(main.rs): fix splitn() function to collect the result into a Vec<&str>
- feat(main.rs): add printing of PR ID, Owner, and Repo variables

chore: split parts

---

src/main.rs

- chore(main.rs): comment out unused code related to PCU_PULL_REQUEST variable
- fix(main.rs): fix indexing issue in changelog_update function

chore: move back in

---

src/main.rs

- chore(main.rs): comment out unused code and add code to check if the head is a branch and print the result
- chore(main.rs): add code to print the statuses of the repository
- chore(main.rs): comment out unused code related to getting branch name and pull request

chore: explore git2 to determine pr

---

src/main.rs

- chore(main.rs): remove unused import and commented code
- feat(main.rs): change variable name from pr_id to pr_number for clarity

fix: pr number (not id)

---

src/main.rs

- chore(main.rs): add check for the type of reference in the main function
- feat(main.rs): print the target of the head reference in the main function

chore: get the kind of the head

---

src/main.rs
src/pr_title.rs

- fix(main.rs): remove unnecessary println statement
- feat(pr_title.rs): make kind and description fields public

chore: remove print of pull list

---

Cargo.toml
src/main.rs

- chore(Cargo.toml): add eyre crate as a dependency
- chore(main.rs): remove unused imports
- feat(main.rs): add support for updating changelog

chore: tidy up and make a mess

---

src/main.rs

- chore(main.rs): add debug print statements for committing changelog
- feat(main.rs): iterate over files in current directory and print their paths

chore: check file list

---

src/main.rs

- chore(main.rs): add print statements to show repo state before and after commit
- fix(main.rs): fix typo in println statement

chore: track repo status before and after

---

src/client.rs
src/lib.rs
src/main.rs

- feat(client): add Client struct
- feat(lib): expose Client struct
- chore(main): comment out remote push code

feat: Client to control interfaces

---

src/main.rs

- chore(main.rs): comment out unused code in changelog_update function
- refactor(main.rs): simplify getting pull_release in changelog_update function

chore: use get from pull request handler

---

src/client.rs

- fix(client.rs): change variable name from pull_release to pull_request
- feat(client.rs): add support for empty pull_request environment variable

fix: crash when pull request doesn't exist

---

src/client.rs
src/main.rs

- feat(client.rs): add method pr_number_as_u64 to convert pull request number to u64
- feat(client.rs): add method pull_release_title to fetch pull request release title
- feat(main.rs): update changelog with pull request information

chore: move getting pull request details to client

---

Cargo.toml
src/client.rs
src/error.rs
src/lib.rs
src/main.rs
src/pr_title.rs

* feat(client.rs): add support for thiserror crate
* fix(client.rs): fix import statements and add missing imports
* feat(client.rs): add new methods and fields to Client struct
* feat(client.rs): implement new method to calculate section and entry for changelog update
* feat(client.rs): implement new methods to get section and entry from Client struct
* feat(client.rs): implement new method to get owner, repo, and pr_number from pull_request URL
* feat(client.rs): implement new method to get title from pull request
* fix(main.rs): fix import statements and add missing imports
* feat(main.rs): add error handling to main function
* feat(main.rs): add async keyword to main function
* feat(main.rs): add error handling to changelog_update function
* feat(main.rs): add async keyword to …

feat: move pr_title to client

---

src/main.rs

* fix(main.rs): fix import statement for Error from pcu_lib
* feat(main.rs): handle Error::EnvVarPullRequestNotFound and return early if on main branch
* feat(main.rs): create entry in changelog using client.create_entry() method
* feat(main.rs): print client details using println!("Client: {:#?}", client)

fix: incorrect method call to create entry

---

src/client.rs
src/main.rs

* feat(client.rs): add support for changelog file name configuration
* fix(main.rs): remove unused constant CHANGELOG_FILENAME
* refactor(main.rs): update changelog file name retrieval logic

chore: move get changelog into client

---

src/client.rs
src/error.rs
src/pr_title.rs

* feat(client.rs): add method to update changelog
* fix(client.rs): fix typo in error message
* fix(pr_title.rs): fix method name to match convention

feat: move update the changelog to client

---

src/main.rs

* feat(main.rs): add support for updating changelog file
* fix(main.rs): fix import statement for fs and path modules
* chore(main.rs): print changelog content after updating

feat: update changelog

---

src/main.rs

* refactor(main.rs): remove unnecessary print statement and refactor print_changelog function
* feat(main.rs): add print_changelog function to display changelog

refactor: printing of changelog

---

src/client.rs
src/main.rs

* feat(client.rs): add method to retrieve repository state
* chore(main.rs): print repository state

feat: print repo state

---

src/client.rs

* refactor(client.rs): remove unnecessary line breaks and indentation in print_long function
* chore(client.rs): update comments in print_long function

fix: format updates

---

src/client.rs
src/main.rs

* feat(client.rs): add commit_changelog method to Client struct
* fix(main.rs): call commit_changelog method in changelog_update function

feat: commit changelog

---

src/client.rs
src/main.rs

* fix(client.rs): fix variable name in commit method from _commit_id to commit_id
* feat(client.rs): add branch creation in commit method
* feat(client.rs): implement branch status method to check for differences between local and remote branch

feat: branch status

---

src/client.rs

* refactor(client.rs): remove unnecessary comments and improve code readability
* fix(client.rs): fix comment indentation

chore: tidy up and facilitate test

---

src/client.rs

* chore(client.rs): add debug print statements for commit_changelog and list of branches
* fix(client.rs): fix formatting of output messages in commit_changelog and branch comparison

chore: additional debug statements

---

src/client.rs

* fix(client.rs): fix Client struct declaration by removing #[derive(Debug, Default)]
* feat(client.rs): add git_repo field to Client struct
* fix(client.rs): fix git_repo variable declaration by using self.git_repo instead of repo
* fix(client.rs): fix commit message by removing unnecessary println statement
* fix(client.rs): fix branch variable declaration by using self.branch instead of repo.branch
* fix(client.rs): fix branch_remote variable declaration by using self.git_repo.find_branch instead of repo.find_branch
* fix(client.rs): fix branch_remote.get().target() comparison by using self.git_repo.head() instead of repo.head()

chore: git repo as part of client struct

---

src/client.rs

* chore(client.rs): remove unused variable assignment
* feat(client.rs): print branch name after creating branch

chore: switch force from true to false

---

src/client.rs

* refactor(client.rs): comment out unused code and print statements

chore: no branch update

---

src/client.rs

* fix(client.rs): fix branch_remote_name and branch_upstream_name calls to return Result instead of bool
* refactor(client.rs): update print statement to use debug formatting for remote_name and upstream_name

chore: figure it out

---

src/client.rs

* fix(client.rs): fix variable names and update print statement to display local and remote targets

chore: show me the targets

---

src/client.rs

* fix(client.rs): fix unwrap calls on local and remote targets
* feat(client.rs): add printing of ahead and behind commits between local and remote branches

chore: ahead and behind

---

src/client.rs
src/main.rs

* feat(client.rs): add branch_list method to retrieve a list of branches
* fix(client.rs): format branch_list output to include branch name and type
* fix(client.rs): remove unnecessary println statements in branch_status method
* fix(main.rs): print branch list and branch status in changelog_update function

chore: tidy up

---

src/client.rs
src/main.rs

* chore(client.rs): remove debug print statements
* feat(client.rs): add push_changelog method to push changes to remote repository

feat: push the changelog commit

---

src/client.rs

* chore(client.rs): add repo_url field to Client struct
* refactor(client.rs): modify get_keys function to return repo_url
* refactor(client.rs): modify push_changelog function to use branch_list function

chore: just origin

---

src/client.rs

* chore(client.rs): refactor code to use RemoteCallbacks for authentication
* fix(client.rs): fix formatting and indentation

chore: default credential callback

---

src/client.rs

* fix(client.rs): reorganize code to connect to remote before setting push options
* feat(client.rs): add print statements for remote connection and push options

chore: bit more info!

---

src/client.rs
src/main.rs

* fix(client.rs): hardcode the path to the SSH private key file
* chore(main.rs): remove unnecessary print statement

fix: set correct ssh key

---

src/client.rs

* fix(client.rs): change git2::Direction to Direction
* feat(client.rs): add authentication for remote connection
* feat(client.rs): establish connection with remote
* feat(client.rs): push changes to remote

feat: add authentication for remote connection

---

.circleci/config.yml

* chore(config.yml): add step to manage SSH keys and print SSH key fingerprints

chore: inspect ssh keys

---

.circleci/config.yml
src/client.rs

* chore(config.yml): add step to clear SSH key before adding new SSH keys

chore: clear down default ssh key

---

src/client.rs

* chore(client.rs): remove unused code for adding remote push
* feat(client.rs): add support for finding branch and pushing to remote

chore: get refspec from branch

---

.circleci/config.yml
CHANGELOG.md
src/client.rs

* chore(config.yml): rename GPG key environment variable from GPGKEY to BOT_GPG_KEY

ci(security): adopt new ci bot signature

---

.circleci/config.yml
CHANGELOG.md
src/client.rs

* chore(config.yml): remove gpg.format from git config
* fix(config.yml): re-order steps to add gpg-key and git-config after ssh-add

ci: reorder ssh and gpg and git steps

---

.circleci/config.yml
CHANGELOG.md
src/client.rs
src/error.rs

* refactor(client.rs): remove commented out code for connecting to remote and setting push options

refactor: remove commented out code

---

CHANGELOG.md
src/client.rs

* fix(client.rs): remove unused code and change commit_signed method signature

chore: return to using none in commit_signed

---

CHANGELOG.md
Cargo.toml
src/client.rs
src/main.rs

* chore(main.rs): initialize env_logger
* feat(main.rs): replace println statements with log::info and log::error

feat: logger and logging 

---

CHANGELOG.md
src/main.rs

* chore(main.rs): replace println! statements with log::debug! and log::info! statements
* chore(main.rs): add conditional logging for print_changelog function

chore: replace printlns with log macros

---

CHANGELOG.md
src/main.rs

* refactor(main.rs): replace print statements with log statements in changelog_update function

refactor: main update to use logs instead of println

---

CHANGELOG.md
src/client.rs
src/error.rs

* chore(client.rs): refactor code to improve readability and maintainability
* fix(client.rs): fix unused constant warning
* feat(client.rs): add support for signing commits with GPG
* fix(error.rs): add new error variants for signing process

feat: sign the commit using gpg

---

src/client.rs

* chore(client.rs): remove debug print statements
* feat(client.rs): add support for signing commits with GPG

chore: decorate signing with log messages

---

CHANGELOG.md
src/client.rs

* chore(client.rs): replace print statements with log statements in Client implementation

chore: display messages using logging

---

CHANGELOG.md
src/pr_title.rs

* refactor(pr_title.rs): replace print statements with log statements for debugging
* fix(pr_title.rs): fix typo in log statement

refactor: replace println with logging

---

.circleci/config.yml
CHANGELOG.md
src/main.rs

Log the full change log only at the trace level.

fix: change log level from Debug to Trace in run_update function

---

CHANGELOG.md
src/main.rs

* fix(main.rs): change default log level to 'off'
* refactor(main.rs): separate filter_module for 'pcu' and 'pcu_lib'

fix: setup of logging for environment or cli

---

Cargo.toml

As changes required to keep-a-changelog to assure compliant changelogs are generated have been adopted by the project return to using the version from crates.io.

fix: update keep-a-changelog dependency from git branch to version 0.1.3

---

CHANGELOG.md
Cargo.toml
src/main.rs

Initial pull request to establish config management based on environment and toml file.

feat: add config crate to Cargo.toml and implement get_settings function in main.rs

---

.circleci/config.yml
src/main.rs

* ci: reduce verbosity level of pcu command from -vvv to -vv in Update changelog job
* refactor: simplify log messages for better readability

refactor: simplify log messages for better readability

---

CHANGELOG.md
src/main.rs

* refactor(main.rs): remove file source from config builder
* feat(main.rs): add error handling for settings configuration

feat: add error handling for settings

---

CHANGELOG.md
src/error.rs
src/main.rs

* feat(error.rs): add Config error type to Error enum
* refactor(error.rs): rename IOError to IO and Utf8Error to Utf8
* refactor(main.rs): modify get_settings function to return Result
* feat(main.rs): add default settings in get_settings function

feat: set defaults for settings

---

CHANGELOG.md
src/main.rs

* fix(main.rs): import HashMap from std::collections
* chore(main.rs): add default values for signature_key and commit_msg in get_settings function

chore: add default values required by client module

---

CHANGELOG.md
src/client.rs
src/error.rs
src/main.rs

* fix(client.rs): add Config struct and use it to pass settings to Client constructor
* feat(client.rs): add support for setting branch, pull request, and default change log file name through Config struct
* fix(error.rs): update error message for DefaultChangeLogNotSet
* feat(main.rs): pass settings to Client constructor in main function

feat: add support for using settings to configure client

---

CHANGELOG.md
src/client.rs
src/main.rs

* refactor(client.rs): remove unused constant SIGNATURE_KEY and DEFAULT_CHANGELOG_COMMIT_MSG
* fix(client.rs): fix typo in commit_message setting key in get_settings function

refactor: migrate const to  settings

---

CHANGELOG.md
Cargo.lock
README.md

* docs(README.md): update README with badges, feature set, CLI usage, license, and contribution sections

docs: update readme for first release

---

.circleci/config.yml
CHANGELOG.md

* ci(config.yml): uncomment and fix cargo release command to use NEXTSV_LEVEL variable
* ci(config.yml): uncomment and fix conditional statement for release readiness

 ci: add step to remove original SSH key from agent

---

CHANGELOG.md

* chore(CHANGELOG.md): add release date to version 0.1.0
* feat(CHANGELOG.md): add comparison URLs for unreleased and version 0.1.0

docs: update changelog with new unreleased changes

---

CHANGELOG.md
release.toml

* fix(release.toml): update pre-release-replacements in CHANGELOG.md to include version and date

chore: update unreleased with version and date

---

CHANGELOG.md
release.toml

* chore(release.toml): remove pre-release-replacement for pcu in README.md and src/lib.rs
* feat(release.toml): add pre-release-replacement for [Unreleased] in CHANGELOG.md

chore: remove failing replacements

---

CHANGELOG.md
release.toml

* chore(release.toml): update pre-release-replacements in CHANGELOG.md to properly format version and date
* chore(release.toml): update pre-release-replacements in CHANGELOG.md to properly format tag name

chore: add search that yields only one response

---

.circleci/config.yml
CHANGELOG.md

* chore(circleci): add echo command to print CARGO_HOME variable
* chore(circleci): update changelog command to use pcu -vv

chore: test for value of CARGO_HOME

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/main.rs
src/pr_title.rs

* chore(Cargo.toml): update eyre dependency to color-eyre version 0.6.3
* feat(main.rs): replace eyre import with color_eyre import
* feat(pr_title.rs): replace eyre import with color_eyre import

chore: update eyre to color-eyre

---

CHANGELOG.md
src/client.rs
src/main.rs

* chore(client.rs): add debug logging for owner, repo, pr_number, and repo_url
* feat(main.rs): add debug logging for settings of github client

chore: additional debug info for octocrab instance setup

---

CHANGELOG.md
src/client.rs

* refactor(client.rs): refactor code to use Arc for Octocrab instance and handle personal access token configuration
* feat(client.rs): add auth support for Octocrab library to interact with GitHub API

feat: add octocrab authentication by personal access token

---

CHANGELOG.md
src/client.rs

refactor: improve error handling and add debug logs for octocrab client

---

CHANGELOG.md
src/client.rs

refactor: improve logging for Octocrab instance and pull request handler acquisition

---

CHANGELOG.md
Cargo.toml

feat: add categories field with development-tools::build-utils and command-line-utilities values

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/pr_title.rs
tests/data/expected_changelog.md

* chore(Cargo.lock): update versions of http-body-util, httparse, memchr, miniz_oxide, subtle
* feat(Cargo.lock): add support for keep-a-changelog from git repository
* fix(src/pr_title.rs): adjust formatting for PR title and add link to PR in changelog
* test(tests/data/expected_changelog.md): update changelog with PR link and adjust formatting

feat: add reference link for PR in title

---

CHANGELOG.md
src/pr_title.rs

feat: add support for generating repository URL from PR URL

---

CHANGELOG.md
src/pr_title.rs

feat: add support for parsing changelog with repository URL in ChangelogParseOptions

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock
src/pr_title.rs

* chore(Cargo.lock): update syn dependency version to 2.0.68
* chore(Cargo.lock): update bitflags version to 2.6.0
* chore(Cargo.lock): update cc version to 1.0.100
* chore(Cargo.lock): update lazy_static version to 1.5.0
* chore(Cargo.lock): update proc-macro2 version to 1.0.86
* chore(Cargo.lock): update serde_json version to 1.0.118
* chore(Cargo.lock): update subtle version to 2.6.1
* chore(Cargo.lock): update syn version to 2.0.68
* chore(Cargo.lock): update tinyvec version to 1.6.1
* chore(Cargo.lock): update uuid version to 1.9.1
* chore(Cargo.lock): update syn version to 2.0.68
* fix

fix: fix method signature requirements

---

.circleci/config.yml
CHANGELOG.md

ci: restore build of pcu package from main branch

---

CHANGELOG.md
src/pr_title.rs
tests/data/expected_changelog_issue_172.md

* fix(pr_title.rs): remove unnecessary split and collect operations in entry variable assignment
* feat(pr_title.rs): add debug log for final entry after pr id check
* test(pr_title.rs): add test for parsing PR title with issue 172 and verifying commit type, scope, and breaking change
* test(pr_title.rs): add test for updating change log with issue 172, including adding new feature and updating orb version

fix: pr title elided (issue #172)

---

.circleci/config.yml
CHANGELOG.md
src/main.rs

ci: add --early-exit flag to pcu command in Update changelog job

---

.circleci/config.yml
CHANGELOG.md
src/main.rs

ci: rename update changelog step and add early exit flag to pcu command

---

.circleci/config.yml
.circleci/success.yml
.circleci/validation.yml
CHANGELOG.md

* refactor(.circleci/config.yml): simplify config by using toolkit orb
* feat(.circleci/validation.yml): add new validation workflow
* feat(.circleci/success.yml): add new success workflow

ci: adopt toolkit and configure to use setup config with validation and success

---

.circleci/config.yml
.circleci/validation.yml
CHANGELOG.md

* chore(.circleci/validation.yml): update toolkit version to 0.16.0
* refactor(.circleci/validation.yml): replace pr-changelog-update job with toolkit/update_changelog
* feat(.circleci/validation.yml): add ssh_fingerprint, min_rust_version, install_from_github parameters to toolkit/update_changelog job

ci: adopt updated toolkit and set install_from_github flag

---

.circleci/config.yml
CHANGELOG.md

* refactor(.circleci/config.yml): replace script parameters with pipeline flags
* feat(.circleci/config.yml): add branch parameter to test_last_committer command

fix: parameterise pipeline flags

---

CHANGELOG.md
renovate.json

chore: update renovate configuration with new rules and settings

---

.circleci/config.yml
CHANGELOG.md

* chore(circleci/config.yml): update toolkit version from 0.17.0 to 0.18.0
* fix(circleci/config.yml): correct end_success job to toolkit/end_success

ci: adopt end_success from toolkit

---

.circleci/config.yml
CHANGELOG.md

* chore(circleci/config): update toolkit version and remove redundant commands and jobs
* feat(circleci/config): replace test_update_changelog job with toolkit/update_changelog

feat: adopt update changelog from toolkit

---

CHANGELOG.md
src/main.rs

fix: move settings initialization after logging initialization

---

CHANGELOG.md
src/client.rs
src/main.rs

* feat(client.rs): add trace logs for settings, branch, pull_request and log
* fix(main.rs): remove trace log for github client settings
* style(main.rs): change log format for settings from inline to pretty-print

chore: trace config settings

---

CHANGELOG.md
src/client.rs

chore: add trace log for pcu_pull_request variable

---

.circleci/config.yml
CHANGELOG.md

ci: upgrade jerus-org/circleci-toolkit orb from 0.20.0 to 0.23.0

---

CHANGELOG.md
Cargo.toml
src/client.rs
src/error.rs
src/main.rs

* feat: add version update and release functionality to changelog
* feat(client.rs): add methods to update and release versions in changelog
* feat(main.rs): add command line options for update and release operations
* feat(error.rs): add error type for invalid version
* chore(Cargo.toml): add chrono dependency for date handling

feat: add release function to move changelog unreleased section to new version

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock
src/client.rs
src/main.rs

* feat(client.rs): add functionality to write release notes to a file
* fix(main.rs): change clap annotation to arg for release command

feat: write release notes

---

.circleci/config.yml
CHANGELOG.md
src/client.rs
src/main.rs

* feat(config.yml): update description for pcu_halt_signal
* feat(client.rs): add is_default_branch function to check if current branch is default
* refactor(main.rs): move early_exit flag from Cli to PullRequest struct
* refactor(main.rs): refactor main function to handle PullRequest and Release separately
* feat(main.rs): add check for default branch in run_update function
* feat(main.rs): add get_client function to initialize client
* feat(main.rs): add default_branch to settings in get_settings function
* feat(main.rs): set commit_message override based on command in get_settings function

refactor: into PullRequest and Release commands and structure app accordingly

---

.circleci/config.yml
CHANGELOG.md
src/client.rs

ci: change order of pcu command parameters to correctly apply --early-exit flag

---

CHANGELOG.md
src/client/mod.rs
src/client/pull_request.rs
src/error.rs
src/main.rs

* refactor(client.rs): extract pull request handling into separate module
* feat(client.rs): add support for command option in settings
* fix(error.rs): add CommandNotSet error type
* refactor(main.rs): set command option in settings based on command type

refactor: extract pull request handling from client to separate struct

---

.circleci/config.yml
CHANGELOG.md
src/main.rs

ci: add branch specification to cargo install command in CircleCI config

---

CHANGELOG.md
src/client/pull_request.rs

feat: add branch check to prevent actions on main or master branches

---

CHANGELOG.md
src/client/mod.rs
src/client/pull_request.rs
src/main.rs

* feat(client/mod.rs): add support for deserializing settings into HashMap
* refactor(client/mod.rs): improve log readability by formatting settings output
* refactor(main.rs): enhance settings log message with a descriptive prefix

chore:tidy up logging

---

.circleci/config.yml
CHANGELOG.md
src/client/pull_request.rs
src/main.rs

* refactor: remove api_token_key from CircleCI config
* refactor(pull_request.rs): remove branch and default_branch handling
* feat(main.rs): add environment variable for branch handling in run_pull_request function

chore: move branch check for main earlier in logic

---

CHANGELOG.md
src/client/mod.rs
src/main.rs

* feat(client/mod.rs): add unreleased field to Client struct
* refactor(client/mod.rs): update_unreleased method now mutates self
* refactor(client/mod.rs): release_unreleased method now uses self.changelog instead of log_file argument
* feat(client/mod.rs): add make_release method to create a new release on GitHub
* refactor(main.rs): get_client now returns a mutable Client
* feat(main.rs): add logic to commit, push and make a release after updating unreleased section in changelog

feat: add make_release method to create a new release on GitHub

---

.circleci/config.yml
CHANGELOG.md
src/main.rs

* feat(.circleci/config.yml): add make_release job to CircleCI configuration
* chore(.circleci/config.yml): replace toolkit/make_release with make_release in workflows

feat: add make_release job to CircleCI configuration to use pcu

---

CHANGELOG.md
src/cli.rs
src/client/mod.rs
src/error.rs
src/main.rs

* feat(cli.rs): add new cli module
* refactor(main.rs): move cli related code to cli module
* fix(main.rs): change 'release' to 'semver' in run_release function
* feat(main.rs): add condition to update changelog in run_release function

feat: add condition to update changelog in run_release function and refactor cli to module

---

CHANGELOG.md
src/client/mod.rs
src/error.rs

* feat(client/mod.rs): add get_commitish_for_tag function to get commit for a specific tag
* refactor(client/mod.rs): refactor make_release function to use get_commitish_for_tag
* feat(error.rs): add TagNotFound error type

feat: add get_commitish_for_tag and refactor make_release function

---

.circleci/config.yml
CHANGELOG.md

* feat(.circleci/config.yml): add parameters for version, specific_version, publish, first_release
* refactor(.circleci/config.yml): update commands for creating Github release and publishing update

feat: add change release for pcu release

---

.circleci/config.yml
CHANGELOG.md
src/cli.rs
src/client/mod.rs
src/main.rs

* feat(.circleci/config.yml): remove gh installation and usage
* feat(cli.rs): add Display trait for Commands enum
* feat(client/mod.rs): add support for personal access token in octocrab instance
* refactor(main.rs): move logging of branch, PR ID, owner, and repo to run_pull_request function
* feat(main.rs): add logging for command execution error and update changelog flag
* chore(main.rs): remove redundant logging from get_client function

chore: increase logging and replace octocrab initialisation

---

CHANGELOG.md
src/client/mod.rs

* feat(client/mod.rs): add owner and repo fields to Client struct
* refactor(client/mod.rs): update owner and repo methods to return new fields
* feat(client/mod.rs): add logic to set owner and repo from environment variables
* refactor(client/mod.rs): update octocrab instance creation with new owner and repo fields

fix: add owner and repo to the client structure so that is available to all commands

---

CHANGELOG.md
src/change_log.rs
src/client/mod.rs
src/lib.rs

* feat(change_log.rs): add new file for handling release notes
* feat(client/mod.rs): implement ReleaseNotesProvider for Changelog
* refactor(client/mod.rs): move release notes generation to Changelog
* feat(lib.rs): include change_log module in library

feat: add release notes trait to generate release notes from changelog

---

CHANGELOG.md
src/main.rs

feat: add support for GITHUB_TOKEN environment variable

---

.circleci/config.yml
CHANGELOG.md
src/change_log.rs

* fix(config.yml): add condition to check if SEMVER is not empty before creating Github release
* feat(change_log.rs): add "What's Changed" section and version specific description to release notes body

ci: release production conditional on SEMVER value existing

---

.circleci/config.yml
CHANGELOG.md

refactor: extract repeated code into commands set_senmver, make_cargo_release, make_github_release

---

.circleci/config.yml
CHANGELOG.md

* feat(config.yml): update toolkit version to 0.24.0
* refactor(config.yml): remove redundant commands and jobs related to release
* fix(config.yml): replace make_release job with toolkit/make_release in workflows

ci: adopt revised toolkit

---

CHANGELOG.md
src/client/mod.rs

* feat(client/mod.rs): add logging for branch details
* refactor(client/mod.rs): change branch retrieval to use match statement for better error handling

fix: handle case were we are pushing from the main branch

---

CHANGELOG.md
src/client/mod.rs

fix: default branch name to 'main' if branch is not specified

---

CHANGELOG.md
src/client/mod.rs

chore: add logging for tag retrieval in get_commitish_for_tag function

---

CHANGELOG.md
src/client/mod.rs
src/main.rs

* feat(client/mod.rs): add version parameter to push_changelog function
* refactor(client/mod.rs): enhance logging and push_refs handling in push_changelog function
* refactor(main.rs): update push_changelog calls to match new function signature

fix: push the version tag to the repo

---

CHANGELOG.md
src/client/mod.rs
src/main.rs

fix: add optional tag parameter to commit_changelog and commit_changelog_gpg functions

---

CHANGELOG.md
src/client/mod.rs

chore: add trace log for .git/refs directory content

---

CHANGELOG.md
src/client/git_ops.rs

* feat(git_ops.rs): add fs::read_to_string to imports
* refactor(git_ops.rs): remove unused version parameter in push_changelog function
* refactor(git_ops.rs): improve logging of list_tags function
* refactor(git_ops.rs): comment out unused tag_ref logic in push_changelog function
* feat(git_ops.rs): enhance list_tags function to read file contents

chore: more precise look at ref and remove from check

---

CHANGELOG.md
src/client/git_ops.rs

chore: add trace logs for debugging in list_tags function

---

CHANGELOG.md
src/client/git_ops.rs

fix: correct format of version_tag in tag_ref string

---

CHANGELOG.md
src/client/mod.rs
src/main.rs
src/ops/make_release.rs

* refactor(client/mod.rs, main.rs, ops/make_release.rs): remove unreleased field from Client struct, refactor run_release function in main.rs, simplify make_release function in ops/make_release.rs

refactor: run_release function in main.rs and simplify make_release function

---

CHANGELOG.md
src/ops/git_ops.rs

refactor: remove unused import and code, refactor tag_ref assignment and logging

---

CHANGELOG.md
src/main.rs

fix: pass version to push_changelog function instead of None

---

CHANGELOG.md
src/client/mod.rs
src/main.rs

fix: replace 'svs_root' and 'scs_root' with 'dev_platform' in client/mod.rs and main.rs

---

CHANGELOG.md
src/client/mod.rs

fix: change head reference from 'main' to 'HEAD' in ChangelogParseOptions

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/client/mod.rs
src/client/pull_request.rs
src/error.rs
src/pr_title.rs

* feat: replace octocrab with octocrate in client and pull_request modules
* fix: change pr_number type from u64 to i64 in client and pr_title modules
* feat: add octocrate error handling in error module

feat: replace octocrab with octocrate in client and pull_request modules

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/client/pull_request.rs
src/error.rs
src/ops/git_ops.rs
src/ops/make_release.rs
src/utilities/release_notes_provider.rs

* refactor: replace octocrab with octocrate in various modules
* fix(error.rs): correct error message from Octocrab to Octocrate
* feat(make_release.rs): implement create_release functionality with octocrate
* feat(release_notes_provider.rs): add ReleaseNotes struct

refactor: replace octocrab with octocrate in various modules

---

.circleci/config.yml
CHANGELOG.md

ci: upgrade jerus-org/circleci-toolkit orb version from 0.25.0 to 1.0.0

---

CHANGELOG.md
src/client/mod.rs
src/ops/git_ops.rs
src/ops/make_release.rs

* refactor(client/mod.rs): remove settings field from Client struct
* refactor(client/mod.rs): add git_api, default_branch, commit_message fields
* refactor(git_ops.rs, make_release.rs): refactor methods to use new fields

refactor: remove settings field from Client struct, add git_api, default_branch, commit_message fields

---

CHANGELOG.md
src/client/mod.rs
src/error.rs

* fix(client/mod.rs): remove un-authenticated instance creation
* feat(error.rs): add error handling for missing GitHub API private key and authorization

feat!: add GitHub App authentication support

---

.circleci/config.yml
CHANGELOG.md

feat: add pcu-app to context in workflows configuration

---

CHANGELOG.md
src/main.rs

* feat(main.rs): add line limit parameter to print_changelog function
* refactor(main.rs): update print_changelog calls with line limit argument

feat: add line limit parameter to print_changelog function

---

.circleci/config.yml
CHANGELOG.md

ci: increase pcu_verbosity level from -vvv to -vvvv

---

CHANGELOG.md
src/client/mod.rs
src/main.rs

* feat(client/mod.rs): add line_limit field to Client struct
* feat(client/mod.rs): add getter for line_limit
* refactor(main.rs): use line_limit from Client struct in print_changelog function
* style(main.rs): remove unnecessary blank lines and reorder print statements in print_changelog function

feat: add config for line limit

---

CHANGELOG.md
Cargo.toml
src/client/mod.rs

* feat(Cargo.toml): add ansi_term dependency
* feat(client/mod.rs): use ansi_term for styled console output
* refactor(client/mod.rs): improve logging messages for authentication methods

feat: use ansi_term for styled console output

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/ops/git_ops.rs

* feat(cli): add push command to CLI
* feat(circleci): add test-push job to CircleCI config
* feat(cli): add Pushed and Released states to ClState
* feat(cli): implement run_push function
* feat(cli): update run_release function to return ClState::Released
* feat(cli): add push command settings in get_settings function
* feat(lib): add repo_status method in GitOps for Client

feat!: add push command to CLI to push any changes to the remote repository

---

.circleci/config.yml
CHANGELOG.md
src/cli/main.rs
src/lib/ops/git_ops.rs

* feat(main.rs): enhance debug log to include unstaged files
* feat(git_ops.rs): add method to get list of unstaged files in the repository

feat: list the unstaged files

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/client/mod.rs
src/lib/ops/git_ops.rs

* feat(cli/main.rs, lib/client/mod.rs, lib/ops/git_ops.rs): add push_commit method and refactor branch method to branch_or_main
* remove(commented out code): remove unused commented out code in cli/main.rs and lib/ops/git_ops.rs
* feat(lib/ops/git_ops.rs): add get_authenticated_remote method and progress_bar function for push progress tracking

feat: add push_commit method and refactor branch method to branch_or_main

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs

* feat(cli.rs, main.rs): add Commit command to CLI
* refactor(cli.rs): separate Commit and Push commands
* feat(main.rs): add run_commit function
* refactor(main.rs): modify run_push function to only handle push command
* feat(main.rs): add Commit command to get_settings function

feat: add commit and reduce to push to push only

---

CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/ops/git_ops.rs

* feat(cli.rs): add semver option to Push struct and tag_opt method
* refactor(main.rs): use tag_opt method in push_commit call
* refactor(git_ops.rs): change log level from debug, info, warn, error to trace in progress_bar function

feat: add semver option to Push struct and tag_opt method

---

CHANGELOG.md
src/lib/client/pull_request.rs

chore: add logging for pull request response

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib/client/graphql.rs
src/lib/client/mod.rs
src/lib/client/pull_request.rs

* feat: add gql_client and serde dependencies in Cargo.toml
* feat(graphql.rs): add new graphql client module for fetching pull request title
* feat(pull_request.rs): use graphql client as fallback for fetching pull request title

feat: fallback to graphql client for fetching pull request title

---

CHANGELOG.md
src/lib/client/graphql.rs
src/lib/error.rs
src/lib/lib.rs

* feat(graphql.rs): add support for custom headers in GraphQL client
* feat(error.rs): add GraphQLWrapper for handling GraphQL errors
* refactor(graphql.rs, error.rs): improve error handling and logging
* feat(lib.rs): expose GraphQLWrapper in public API

fix: add headers and refine error handling

---

CHANGELOG.md
src/lib/client/graphql.rs
src/lib/client/mod.rs
src/lib/client/pull_request.rs
src/lib/ops/git_ops.rs
src/lib/ops/make_release.rs

* refactor(client): move graphql client initialization to mod.rs
* refactor(client): rename git_api to github_rest
* refactor(pull_request): add graphql client as parameter in new_pull_request_opt
* refactor(git_ops, make_release): replace git_api with github_rest

feat: better organisation of code

---

CHANGELOG.md
src/lib/client/mod.rs

* refactor(client/mod.rs): merge get_github_api into get_github_apis
* feat(client/mod.rs): add support for gql_client with headers in get_github_apis
* refactor(client/mod.rs): return tuple of GitHubAPI and gql_client from get_github_apis

feat: add support for gql_client with headers in get_github_apis

---

CHANGELOG.md
src/lib/client/graphql.rs

fix: add owner and name fields to repository query

---

CHANGELOG.md
src/lib/client/graphql.rs

fix: add skip_deserializing attribute to owner and name fields in Repository struct

---

CHANGELOG.md
src/lib/client/graphql.rs

fix: remove unnecessary owner and name fields from get_pull_request_title query

---

CHANGELOG.md
src/lib/client/pull_request.rs

* refactor(pull_request.rs): remove unused Octocrate instance and use GraphQL for pull request title retrieval

feat: use GraphQL for pull request title retrieval

---

CHANGELOG.md
src/cli/main.rs

chore: remove commented out debug logs and unused code

---

CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/ops/git_ops.rs

* feat(cli): add Rebase command to CLI
* feat(cli): implement run_rebase function in main.rs
* feat(lib): add rebase_next_pr method to GitOps trait in git_ops.rs

feat: add Rebase command to CLI

---

.circleci/config.yml
CHANGELOG.md
src/cli/main.rs
src/lib/client/graphql/mod.rs
src/lib/client/graphql/pr_title.rs
src/lib/client/graphql/prs.rs
src/lib/client/mod.rs
src/lib/ops/git_ops.rs

* feat(graphql): add new graphql module with pr_title and prs submodules
* refactor(graphql): move get_pull_request_title function to pr_title submodule
* feat(client): enable github_graphql in Client struct
* feat(git_ops): add async rebase_next_pr function in GitOps trait
* refactor(git_ops): update rebase_next_pr function to use get_open_pull_requests function

feat: add graphql method to get open pull requests

---

CHANGELOG.md
src/lib/client/graphql/mod.rs
src/lib/client/graphql/prs.rs
src/lib/client/mod.rs
src/lib/client/pull_request.rs

* feat(prs.rs): add PrItem struct and modify get_open_pull_requests method to return Vec<PrItem> instead of Vec<Edge>

feat: add PrItem struct and return Vec<PrItem> instead of Vec<Edge>

---

.markdownlint.json
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/ops/git_ops.rs

feat: add early return if no open pull requests are found

---

.circleci/config.yml
CHANGELOG.md

fix: add condition to execute pcu rebase only if CIRCLE_PULL_REQUEST is set

---

.circleci/config.yml
CHANGELOG.md
src/lib/client/graphql/prs.rs
src/lib/client/mod.rs
src/lib/client/pull_request.rs

* refactor(prs.rs): simplify pull request mapping logic
* fix(client/mod.rs, pull_request.rs): remove "rebase" command check

feat: run rebase only when check run on main

---

.circleci/config.yml
CHANGELOG.md

* fix(.circleci/config.yml): add check for CIRCLE_PULL_REQUEST existence before running pcu
* fix(.circleci/config.yml): correct syntax for checking CIRCLE_PULL_REQUEST in rebase command

ci: add check for pull request before running cl update

---

.circleci/config.yml
CHANGELOG.md

ci: modify conditional logic for result variable and API call

---

CHANGELOG.md
src/lib/client/graphql/label.rs
src/lib/client/graphql/mod.rs
src/lib/ops/git_ops.rs

* feat(graphql): add label.rs for handling labels on PRs
* refactor(graphql): split GraphQL trait into GraphQLLabel and GraphQLPR
* feat(git_ops.rs): implement PR labeling and sorting in rebase_next_pr method

feat: add label support for pull requests

---

CHANGELOG.md
src/lib/client/graphql/label.rs
src/lib/client/graphql/prs.rs

* refactor(label.rs): rename struct GetPullRequestTitle to GetLabelID and change its field
* refactor(prs.rs): remove trace log for pr number

fix: rename GetPullRequestTitle to GetLabelID and remove redundant log trace

---

CHANGELOG.md
src/lib/client/graphql/label.rs

fix: comment out serde rename attribute for label field

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib/client/graphql/label.rs

* feat: add tracing library to Cargo.toml and Cargo.lock
* refactor(label.rs): replace log with tracing for better tracing instrumentation

feat: integrate tracing library for enhanced logging

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/main.rs

* feat: add tracing-subscriber and related dependencies to Cargo.toml
* feat(cli/main.rs): implement tracing logging with EnvFilter
* fix(cli/main.rs): update get_logging function to accept reference to log::LevelFilter
* feat(Cargo.lock): add new dependencies related to tracing-subscriber

feat: add tracing-subscriber for enhanced logging

---

CHANGELOG.md
src/lib/client/graphql/repo.rs

fix: skip deserializing owner and name fields in Repository struct

---

CHANGELOG.md
src/lib/client/graphql/label_pr.rs

fix(label_pr): simplify GraphQL mutation parameters for labeling PRs

---

CHANGELOG.md
src/lib/client/graphql/label_pr.rs

fix(graphql): correct trace log message from vars to mutation in label_pr.rs

---

CHANGELOG.md
src/lib/client/graphql/label_pr.rs

fix(label_pr): replace id with name in Label struct and GraphQL query

---

CHANGELOG.md
src/lib/client/graphql/label_pr.rs

fix(graphql): correct label_id type in mutation from String to ID

---

CHANGELOG.md
src/lib/client/graphql/label_pr.rs

fix: correct typo in GraphQL mutation query in label_pr.rs

---

CHANGELOG.md
src/lib/client/graphql/get_pr_title.rs
src/lib/client/graphql/label_pr.rs

fix(graphql): rename GetPullRequestTitle struct to Data and enhance Data struct in label_pr.rs

---

CHANGELOG.md
src/lib/client/graphql/label_pr.rs

refactor(label_pr): remove debug trace statement from GraphQLLabelPR implementation

---

CHANGELOG.md
src/lib/client/graphql/get_open_prs.rs
src/lib/ops/git_ops.rs

- add filtering by login in rebase_next_pr
- feat: make login field public in PrItem

feat: add filtering by login in rebase_next_pr

---

CHANGELOG.md
src/lib/ops/git_ops.rs

fix(git_ops): add early exit for no open PRs scenario following filter to login

---

CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/client/graphql/get_open_prs.rs
src/lib/ops/git_ops.rs

- refactor(logging): replace log with tracing in GraphQLGetOpenPRs and GitOps
- fix(ops): pass login option to rebase_next_pr function

feat(cli): add login option to rebase command

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs

docs(cli): update Rebase command description to include label application

feat(ci): add label to pull request during rebase

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/client/graphql/get_label_id.rs
src/lib/client/graphql/label_pr.rs
src/lib/ops/git_ops.rs

feat(rebase): add label option for rebase command

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/client/graphql/get_label_id.rs
src/lib/client/graphql/label_pr.rs
src/lib/ops/git_ops.rs

Add support for an optional description when creating or labeling a pull request with the rebase label. This allows users to provide a custom description for the label if it is created.

feat(cli): add description option for rebase label

---

.circleci/config.yml
CHANGELOG.md
src/lib/client/graphql/create_label.rs

fix: update test label in CircleCI config and add description parameter to GraphQL mutation

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/client/graphql/get_label_id.rs
src/lib/client/graphql/label_pr.rs
src/lib/ops/git_ops.rs

feat(cli): add colour option for labels in rebase command

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/ops/git_ops.rs

refactor: rename 'rebase' command to 'label' in CI configuration and CLI

---

CHANGELOG.md
src/lib/client/mod.rs

refactor(client): simplify branch_or_main method using map_or

---

CHANGELOG.md
renovate.json

feat(config): update renovate.json with new configuration options

---

CHANGELOG.md
renovate.json

fix: update rangeStrategy to auto in renovate.json

---

CHANGELOG.md
renovate.json

refactor: remove extends key from renovate.json

---

CHANGELOG.md
renovate.json

chore: remove semanticCommitType from renovate.json

---

CHANGELOG.md
renovate.json

chore: remove semanticCommits setting from renovate.json

---

CHANGELOG.md
renovate.json

chore: remove versioning configuration from renovate.json

---

CHANGELOG.md
renovate.json

chore: remove rangeStrategy from renovate configuration

---

CHANGELOG.md
renovate.json

feat(renovate): add package grouping and regex manager for rust-toolchain

---

CHANGELOG.md
renovate.json

chore: update rangeStrategy to update-lockfile in renovate.json

---

CHANGELOG.md
renovate.json

fix: change rangeStrategy in renovate.json from update-lockfile to replace

---

CHANGELOG.md
renovate.json

fix: update rangeStrategy in renovate.json from replace to bump

---

.circleci/config.yml
CHANGELOG.md

ci: update CircleCI config to use toolkit 1.5.0 and add label_pr job

---

.circleci/config.yml
CHANGELOG.md

chore(circleci): update toolkit orb to version 1.6.1

---

CHANGELOG.md
src/cli/main.rs

fix(cli): pass version to commit_changed_files function in run_release

---

CHANGELOG.md
src/cli/main.rs
src/lib/ops/git_ops.rs

feat(logging): add trace logs for push_commit function

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
sonar-project.properties
src/cli/main.rs
src/lib/client/mod.rs

ci(circleci): update toolkit orb to version 1.9.2 and add security context to workflows

---

.circleci/config.yml
CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs
src/lib/client/mod.rs
src/lib/client/pull_request.rs

refactor!(cli): rename PullRequest to Pr for brevity

---

CHANGELOG.md
renovate.json

fix: enable CircleCI toolkit package in renovate configuration

---

CHANGELOG.md
renovate.json

feat(config): add host rules for CircleCI token in renovate.json

---

CHANGELOG.md
renovate.json

feat(renovate): add sourceUrl for circleci-toolkit orb

---

CHANGELOG.md
renovate.json

fix: update sourceUrl for circleci-toolkit in renovate.json

---

CHANGELOG.md
renovate.json

feat: add authType configuration for CircleCI host in renovate.json

---

.circleci/config.yml
CHANGELOG.md
renovate.json

fix: remove hostRules configuration from renovate.json

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/cli.rs
src/cli/main.rs
src/lib/error.rs
src/lib/lib.rs
src/lib/ops/git_ops.rs
src/lib/workspace.rs

feat(cli): add workspace flag to process packages in the workspace

---

CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs

refactor(cli): make semver optional and handle missing value in release process

---

CHANGELOG.md
src/cli/main.rs

fix(cli): correct tag existence check and release creation logic

---

CHANGELOG.md
src/cli/cli.rs
src/cli/main.rs

feat(cli): add option to release specific workspace package

---

CHANGELOG.md
src/cli/cli.rs

fix(cli): correct typo in release command description

---

.circleci/config.yml
CHANGELOG.md

chore: update CircleCI toolkit orb to version 1.21.0

---

.circleci/config.yml
CHANGELOG.md

- add additional release-flag condition check in workflows
- allow manual trigger of release flow with release-flag parameter

👷 ci(circleci): enhance CircleCI config with new job dependencies  and trigger

---

.circleci/config.yml
CHANGELOG.md
src/cli/main.rs
src/lib/client/mod.rs
src/lib/ops/update_from_pr.rs
src/lib/pr_title.rs

- add commit_emoji field to PrTitle struct
- update regex to parse emoji from PR titles
- modify tests to include emoji cases

✨ feat(pr_title): add commit emoji support

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md

- add blank line for better readability in reproduction steps
- adjust indentation for desktop and smartphone sections for uniformity

💄 style(issue template): improve formatting consistency

---

CHANGELOG.md
src/bin/main.rs
src/cli.rs
src/cli/pull_request.rs

- move run_pull_request to a separate module for better organization
- update imports and function calls accordingly
🔧 chore(cli): remove unused imports and constants
- remove unused ChangeKind import and SIGNAL_HALT constant from main.rs
- clean up CLI imports to improve readability

♻️ refactor(cli): modularize pull request handling

---

.vscode/settings.json
CHANGELOG.md
src/cli.rs
src/cli/pull_request.rs
src/cli/push.rs
src/cli/release.rs
src/ops/git_ops.rs

- remove redundant push_committed function in cli module
- directly use push_commit method for cleaner code
💄 style(vscode): update spelling settings
- add new words to the cSpell.words list for better spell checking
🐛 fix(git_ops): correct variable names and comments
- fix typos in comments and variable names for clarity
- rename istatus to is_status for better readability

♻️ refactor(cli): remove duplicate push_committed function

---

.circleci/config.yml
CHANGELOG.md
src/cli/pull_request.rs
src/client/mod.rs

- update toolkit orb version from 2.1.0 to 2.2.0 for new features
- remove unused commands and jobs for better maintainability
- replace custom update_changelog job with toolkit/update_changelog

👷 ci(circleci): update toolkit orb and streamline config

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft.rs

- remove commented-out code for improved readability and maintainability

♻️ refactor(cmd_draft): clean up get_files_from_path function

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock

- introduce a new 'tools' job in CircleCI to verify tool versions
- ensure consistent environment by checking versions of essential tools

👷 ci(circleci): add tools job to CI configuration

---

.circleci/config.yml
CHANGELOG.md

- add release-flag condition to improve workflow logic and execution

👷 ci(circleci): update workflow conditions

---

CHANGELOG.md
src/ops/git_ops.rs

- add trace logs for username source when setting up credentials
- improve debug capability by logging whether username is from URL or bot user name

✨ feat(git_ops): add trace logging for credential usage

---

CHANGELOG.md
src/ops/git_ops.rs

- add log trace to check if ssh key credential creation is successful or not

🐛 fix(git_ops): add logging for ssh key credential status

---

.circleci/config.yml
.circleci/release.yml
CHANGELOG.md

- create a new release.yml file for release-specific configurations
- migrate release jobs and parameters from config.yml to release.yml
👷 ci(circleci): simplify config by removing release flag
- remove release-flag parameter and related conditions
- eliminate tools job and associated steps from config.yml

👷 ci(circleci): separate release workflow into its own config

---

.circleci/config.yml
CHANGELOG.md

Revert 👷 ci(circleci)  separate release workflow into its own config

---

CHANGELOG.md
src/cli/release.rs
src/client/graphql/get_tag.rs
src/client/graphql/mod.rs
src/ops/git_ops.rs
src/ops/make_release.rs

- implement GraphQLGetTag trait for fetching tag details
- define data structures for deserializing GraphQL response
- integrate query to retrieve tag information, including tagger details

✨ feat(graphql): add get_tag functionality

---

CHANGELOG.md
src/bin/main.rs
src/client/graphql/create_label.rs
src/client/graphql/get_label_id.rs
src/client/graphql/get_open_prs.rs
src/client/graphql/get_pr_id.rs
src/client/graphql/get_repo_id.rs
src/client/graphql/get_tag.rs
src/client/graphql/label_pr.rs
src/ops/git_ops.rs

- change all instances of `tracing` logging to use the `log` crate instead
- ensure consistency in logging across different modules

♻️ refactor(logging): replace tracing with log

---

CHANGELOG.md
src/client/graphql/get_tag.rs

- adjust closing bracket indentation for consistent formatting

💄 style(graphql): fix indentation in get_tag query

---

CHANGELOG.md
src/cli/release.rs
src/cli/release/mode.rs
src/error.rs

- integrate mode module to handle different release paths
- introduce subcommands for version, package, workspace, and current modes
🐛 fix(release): handle missing package error
- add error handling for cases where no package is specified for release
- ensure proper logging and error messages for missing package scenarios
♻️ refactor(release): simplify release logic using match statement
- replace conditional statements with a match structure for clarity
- streamline release process based on selected mode
✨ feat(error): add error variant for no package specified
- introduce NoPackageSpecified error variant to handle missing package scenario
- provide clear error message when package is not provided during release

✨ feat(release)!: add mode-based release management

---

.circleci/release.yml
CHANGELOG.md

- include remove_ssh_key parameter for enhanced security in CI process

👷 ci(circleci): add remove_ssh_key parameter to release workflow

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock
Cargo.toml

- remove unnecessary toolkit/save_next_version job
- streamline make_release job by eliminating redundant steps

👷 ci(circleci): simplify release workflow configuration

---

CHANGELOG.md
renovate.json

- change schedule to run every hour from midnight to 5 AM on the 24th of each month

🔧 chore(config): update renovate schedule for flexibility

---

.circleci/config.yml
.circleci/release.yml
.vscode/settings.json
CHANGELOG.md

- upgrade circleci-toolkit orb from 2.9.1 to 2.11.0 for latest features and bug fixes

Upgrade-toolkit-orb-to-version-2.11.0-for-latest-features-and-fixes

---

CHANGELOG.md
src/bin/main.rs
src/cli/bsky/commands/cmd_draft.rs
src/cli/bsky/commands/cmd_draft/draft.rs
src/cli/bsky/commands/cmd_post.rs
src/cli/bsky/commands/cmd_post/poster.rs
src/cli/pull_request.rs
src/cli/push.rs
src/cli/release.rs
src/client.rs
src/client/graphql/create_label.rs
src/client/graphql/get_label_id.rs
src/client/graphql/get_open_prs.rs
src/client/graphql/get_pr_id.rs
src/client/graphql/get_pr_title.rs
src/client/graphql/get_repo_id.rs
src/client/graphql/get_tag.rs
src/client/graphql/label_pr.rs
src/client/pull_request.rs
src/ops/git_ops.rs
src/ops/make_release.rs
src/ops/update_from_pr.rs
src/pr_title.rs
src/utilities/release_unreleased.rs

- update log statements to utilize format strings for consistency
- improve readability and maintainability of logging code

♻️ refactor(logging): use format strings for logging

---

.circleci/release.yml
CHANGELOG.md

- add SSH key listing to release workflow for better debugging
🔧 chore(changelog): update changelog for PR
- ensure changelog is up-to-date with recent changes and pull requests

🔧 chore(ci): update release workflow

---

.circleci/release.yml
CHANGELOG.md

- replace incorrect `l` command with `ls` to properly list ssh directory contents

👷 ci(circleci): fix ssh directory listing command

---

.circleci/release.yml
CHANGELOG.md

- remove unnecessary ls command from release job
- add remove_ssh_key parameter to workflows for better control

🔧 chore(ci): update release.yml configuration

---

CHANGELOG.md

- add entries for recent changes including workflow simplifications and configuration updates

📝 docs(CHANGELOG): update changelog for unreleased changes

---

.circleci/release.yml
CHANGELOG.md
src/cli/pull_request.rs

- update default_value_t to true for allow_no_pull_request for better ci flexibility
- add logging for client_res and allow_no_pull_request to improve traceability

🐛 fix(cli): change default for allow_no_pull_request to true

---

CHANGELOG.md
renovate.json

- switch from inheritConfig to extends for easier maintenance
- consolidate configuration to a single line for clarity

🔧 chore(renovate): update configuration to extend from remote

---

CHANGELOG.md
renovate.json

- remove unnecessary configuration options for simplification
- retain schedule setting for automated updates

🔧 chore(renovate): update renovate configuration

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft/draft.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter.rs

- implement method to convert tags to hashtags with capitalization and prefix
- enhance Draft struct to utilize hashtags in post processing
✅ test(draft): add unit tests for new hashtag functionality
- test hashtag conversion logic in taxonomies
- ensure draft processing correctly applies hashtags
- verify file creation in write_posts and cleanup operations

✨ feat(draft): add hashtag formatting to taxonomies

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/bsky/commands/cmd_draft.rs
src/cli/bsky/commands/cmd_draft/draft.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter.rs
src/cli/bsky/commands/cmd_draft/draft/redirector.rs

- implement new write_redirects method to handle redirects in drafts
💄 style(tests): update test function and path naming
- rename test_get_files_nonexistent_path to test_get_files_non_existent_path
- update path in test to match new naming convention

✨ feat(cli): add redirect functionality to draft command

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft/draft/front_matter.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter/bluesky.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter/extra.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter/taxonomies.rs

- introduce Bluesky struct with description and tags fields
- implement description and tags methods for Bluesky
- add Extra struct containing optional Bluesky
- create Taxonomies struct with tags field and methods for tags and hashtags conversion

♻️ refactor(front_matter): modularize and streamline code structure

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft.rs
src/cli/bsky/commands/cmd_draft/draft.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter.rs

- add trace logs to indicate path usage
- update log level from trace to info for blog post output
- add debug logs for building post text and link creation

🐛 fix(cli): enhance logging for draft command

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft/draft.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter.rs

- add warning log for missing post links
- ensure postname is encoded using base62
- update post file naming to use encoded postname

🐛 fix(front_matter): correct short link formatting

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft/draft/front_matter.rs
src/cli/bsky/commands/cmd_draft/draft/front_matter/taxonomies.rs
src/error.rs

- rename PostTooCharacters to PostTooManyCharacters for clarity

🐛 fix(front_matter): correct error handling for post length

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft.rs

- use separate logic for path-based and filter-based file retrieval
- improve logging for better traceability of file processing steps

♻️ refactor(cmd_draft): enhance file change handling logic

---

CHANGELOG.md
src/cli/bsky/commands/cmd_draft.rs

- change log level from debug to trace for front matter logging
- improve log granularity by adjusting verbosity level

💄 style(cmd_draft): update log level for front matter

---

CHANGELOG.md
src/ops/git_ops.rs

- add branch status logging when files are staged for commit
- include message for no files to commit for improved clarity

✨ feat(git_ops): enhance logging with branch status and commit info

---

.circleci/release.yml
CHANGELOG.md

- add pcu-app context to the release workflow for enhanced configuration

👷 ci(circleci): update context in release workflow

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/gen-bsky/Cargo.toml

- include "crates/gen-bsky" as a member of the workspace for better project organization and management

🔧 chore(gen-bsky): update cargo package metadata

---

.circleci/config.yml
CHANGELOG.md

- add branch filter to ignore 'main' branch for commit_and_push job

👷 ci(circleci): update workflow branch filter

---

CHANGELOG.md
crates/gen-bsky/src/front_matter.rs
crates/gen-bsky/src/front_matter/bluesky.rs

- replace direct field access with method calls for description and tags
- ensure consistency in accessing optional fields in tests

♻️ refactor(bluesky): update field access in Bluesky struct

---

CHANGELOG.md
crates/gen-bsky/src/front_matter.rs
crates/gen-bsky/src/front_matter/taxonomies.rs

- replace direct tag access with tags() method for improved encapsulation
- update test cases to use tags() method for consistency
- refactor Taxonomies initialization to use new constructor method

♻️ refactor(taxonomies): improve tag handling in Taxonomies struct

---

.gitignore
.vscode/ltex.hiddenFalsePositives.en-GB.txt
.vscode/settings.json
CHANGELOG.md
crates/gen-bsky/src/draft/blog_post.rs
crates/gen-bsky/src/draft/blog_post/front_matter.rs
justfile

- ignore coverage directory to exclude test coverage reports from version control

Add-code-coverage-generation

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/pcu/Cargo.toml

- bump version from 0.0.0 to 0.0.1 in Cargo.toml

📦 build(gen-bsky): update version to 0.0.1

---

CHANGELOG.md
Cargo.lock
crates/gen-bsky/CHANGELOG.md
crates/gen-bsky/Cargo.toml
crates/pcu/CHANGELOG.md
crates/pcu/Cargo.toml

- create CHANGELOG.md for gen-bsky with detailed commit history
- include sections for chore, documentation, new features, bug fixes, refactor, style, test, and other changes
- add changelog file for pcu crate documenting notable changes and enhancements
🔧 chore(workspace): update project structure and dependency configuration
- add gen-bsky and pcu crates to workspace with changelog documentation
- reorganize file structure for better modularity and clarity
- enhance dependency management across crates for consistent development setup

Release-gen-bsky-v0.0.1,-pcu-v0.5.0

---

CHANGELOG.md
crates/gen-bsky/src/lib.rs
crates/gen-bsky/src/post.rs
crates/pcu/src/cli/bsky/commands/cmd_post.rs
crates/pcu/src/error.rs

- introduce PostError variant to handle gen-bsky post errors
- improves error handling and clarity for post-related issues

♻️ refactor(post): rename and restructure post module

---

.vscode/settings.json
CHANGELOG.md
crates/pcu/src/error.rs

- eliminate unused error variants to simplify error handling
- remove unnecessary import of env module

♻️ refactor(error): remove unused error variants

---

CHANGELOG.md
crates/gen-bsky/src/draft.rs
crates/gen-bsky/src/draft/blog_post.rs
crates/gen-bsky/src/draft/blog_post/front_matter.rs
crates/gen-bsky/src/draft/blog_post/front_matter/bluesky.rs
crates/gen-bsky/src/draft/blog_post/front_matter/taxonomies.rs
crates/gen-bsky/src/post.rs
crates/pcu/src/cli/label.rs
crates/pcu/src/cli/pull_request.rs
crates/pcu/src/cli/release.rs
crates/pcu/src/client.rs
crates/pcu/src/client/pull_request.rs
crates/pcu/src/error.rs
crates/pcu/src/ops/git_ops.rs
crates/pcu/src/utilities/release_unreleased.rs
rustfmt-nightly.toml

- delete unnecessary empty comment line for cleaner code appearance

💄 style(config): update rustfmt configuration and apply updated rules

---

CHANGELOG.md
crates/gen-bsky/src/lib.rs

- update module documentation to provide a clearer overview of the tool's functionality
- improve workflow explanations with detailed steps for drafting and publishing
- add examples showcasing complete usage scenarios and benefits of short URLs
- refine code examples for better understanding and error handling

📝 docs(lib): enhance documentation for gen-bsky

---

CHANGELOG.md
crates/gen-bsky/src/draft.rs
crates/gen-bsky/src/lib.rs
crates/pcu/src/cli/bsky/commands/cmd_draft.rs

- convert date to string slice to prevent errors when setting minimum date

📝 docs(lib): enhance documentation and examples

---

.vscode/settings.json
CHANGELOG.md
Cargo.toml
crates/gen-bsky/Cargo.toml
crates/gen-bsky/src/draft.rs
crates/pcu/Cargo.toml

- add tests for string literals, strings, PathBuf, path references
- test behavior with multiple, empty, absolute, and relative paths
- test special characters, order preservation, and duplicates
- ensure method chaining and builder state are tested

✅ test(draft): add comprehensive tests  and documentation for add_path_or_file method

---

CHANGELOG.md
crates/gen-bsky/src/draft.rs

- Add comprehensive documentation for the `Draft` struct
- Include usage patterns and structure details for better clarity
💄 style(draft): reformat comments for improved readability
- Adjust line breaks and indentation in comments
- Ensure consistent formatting across documentation blocks

📝 docs(draft): enhance draft struct documentation

---

CHANGELOG.md
crates/gen-bsky/src/lib.rs

- describe how Bluesky posts are generated using blog post metadata
- explain character limit and error handling for Bluesky posts
- provide example of frontmatter with Bluesky-specific section

📝 docs(lib): add documentation for preparing blog post frontmatter

---

CHANGELOG.md
crates/gen-bsky/src/draft.rs
crates/gen-bsky/src/draft/blog_post.rs
crates/gen-bsky/src/draft/blog_post/front_matter.rs

- add chrono crate to use current date in test case
- replace assert with dynamic date comparison using Utc::now()

✅ test(draft): add comprehensive tests for blog post handling

---

CHANGELOG.md
crates/gen-bsky/src/draft/blog_post/front_matter/extra.rs
crates/gen-bsky/src/draft/blog_post/front_matter/taxonomies.rs

- break long comment into two lines for readability

✅ test(taxonomies): add documentation and enhance test coverage for taxonomies functionality

---

CHANGELOG.md
crates/gen-bsky/README.md
crates/gen-bsky/README.old
crates/gen-bsky/docs/readme/head.md

- add "Gen-bsky Library" section to provide an overview of the library

📝 docs(readme): update readme with gen-bsky library section

---

.circleci/config.yml
PRLOG.md

- rename changelog_updated to prlog_updated for consistency
- update job names and workflow steps to reflect PRLOG usage
- ensure PRLOG.md is correctly handled in workspace operations

👷 ci(circleci): update changelog references to prlog

---

.circleci/config.yml
PRLOG.md

- eliminate obsolete version and package fields from config.yml
- streamline CircleCI configuration by removing redundant settings

👷 ci(circleci): remove unused version and package parameters

---

PRLOG.md
crates/gen-bsky/release.toml
crates/pcu/release.toml
release.toml

- create release.toml for pcu
- set pre-release commit message and tag information

🔧 chore(release): remove unused release configuration

---

PRLOG.md
crates/gen-bsky/src/lib.rs

- add cfg_attr for docsrs to include documentation conditionally

🐛 fix(docs): correct doc attribute for rustdoc configuration
